import { orpc } from "@/lib/orpc";
import {
  RealtimeMessage,
  ThreadEvent,
  ThreadEventSchema,
} from "@/schemas/realtime";
import { useQueryClient } from "@tanstack/react-query";
import { ol } from "motion/react-m";
import usePartySocket from "partysocket/react";
import { createContext, ReactNode, useContext, useMemo } from "react";

interface ThreadRealtimeProviderProps {
  children: ReactNode;
  threadId: string;
}

type ThreadRealtimeContextValue = {
  send: (event: ThreadEvent) => void;
};

const ThreadRealtimeContext = createContext<null | ThreadRealtimeContextValue>(
  null,
);
export function ThreadRealtimeProvider({
  children,
  threadId,
}: ThreadRealtimeProviderProps) {
  const queryClient = useQueryClient();

  type ThreadListOptions = ReturnType<
    typeof orpc.message.thread.list.queryOptions
  >;

  type ThreadQueryData = Awaited<ReturnType<ThreadListOptions["queryFn"]>>;

  const socket = usePartySocket({
    host: "http://localhost:8787",
    room: `thread-${threadId}`,
    party: "chat",

    onMessage(e) {
      try {
        const parsed = JSON.stringify(e.data);
        const result = ThreadEventSchema.safeParse(parsed);

        if (!result.success) {
          console.log("Invalid Thread Event");
          return;
        }

        const evt = result.data;

        if (evt.type === "thread:reply:created") {
          //Use the same key generated by orpc
          const replyObject = evt.payload.reply as RealtimeMessage;
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,

            (old) => {
              if (!old) return old;

              const reply = {
                ...replyObject,
                reactions: Array.isArray(replyObject.reactions)
                  ? replyObject.reactions
                  : [],
              } as ThreadQueryData["messages"][number];

              return {
                ...old,
                messages: [...old.messages, reply],
              };
            },
          );
        }

        if (evt.type === "thread:reaction:updated") {
          const { messageId, reactions, threadId: tid } = evt.payload;
          if (threadId !== tid) {
            return;
          }

          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId },
          });

          queryClient.setQueryData(listOptions.queryKey, (old) => {
            if (!old) return old;

            if (messageId === threadId) {
              return {
                ...old,
                parent: { ...old.parent, reactions },
              };
            }
            return {
              ...old,
              messages: old.messages.map((m) =>
                m.id === messageId ? { ...m, reactions } : m,
              ),
            };
          });
          return;
        }
        return;
      } catch {
        console.log("something went wrong");
      }
    },
  });

  const value = useMemo<ThreadRealtimeContextValue>(() => {
    return {
      send: (event) => {
        socket.send(JSON.stringify(event));
      },
    };
  }, [socket]);

  return (
    <ThreadRealtimeContext.Provider value={value}>
      {children}
    </ThreadRealtimeContext.Provider>
  );
}

export function useThreadRealtime() {
  const ctx = useContext(ThreadRealtimeContext);

  if (!ctx) {
    throw new Error(
      "useThreaD realtime  must be used within a ThreadRealtimeProvider",
    );
  }

  return ctx;
}

export function useOptionalThreadRealtime(): ThreadRealtimeContextValue | null {
  return useContext(ThreadRealtimeContext);
}
